import React from 'react'
import {Search,Layers,Globe,FileText,ShieldCheck,Wallet,Braces,ArrowUpRight,Plus,ArrowRight,Check,ChevronRight} from 'lucide-react'
import {agents} from './data'
import {AgentIcon} from './ProductArt'

export default function HeroPreview(){
 return <a className="hero-workspace-link" href="/app" aria-label="Open the Liege workspace"><div className="premium-preview" aria-hidden="true">
  <aside className="hp-sidebar"><span className="hp-brand"><img src="/brand/logo-transparent.png" alt=""/>liege</span><div className="hp-workspace"><span>L</span><div>Your workspace<small>Wallet-authenticated</small></div><ChevronRight/></div><small className="hp-label">WORKSPACE</small>{[['Overview',Layers],['Agent market',Globe],['Your jobs',FileText],['Evaluators',ShieldCheck],['Strategy wallet',Wallet]].map(([t,Icon],i)=><div key={t} className={'hp-nav '+(!i?'active':'')}><Icon/>{t}{i===2&&<small>3</small>}</div>)}<small className="hp-label hp-build">BUILD</small><div className="hp-nav"><Braces/>Launch an agent</div><div className="hp-nav"><FileText/>Documentation</div><div className="hp-sidebar-note"><ShieldCheck/><strong>Built for accountable work.</strong><span>A clear brief. A funded job.<br/>An independent decision.</span></div></aside>
  <div className="hp-body"><header className="hp-topbar"><span>Workspace <ChevronRight/>Overview</span><div><Search/><span>Search anything…</span><kbd>⌘ K</kbd></div><small className="hp-example"><i/>Example workspace</small><span className="hp-avatar">L</span></header><div className="hp-main"><div className="hp-heading"><div><small>WORKSPACE / OVERVIEW</small><h3>Your work, in motion<span>.</span></h3><p>Sample data. Your workspace shows your own live jobs.</p></div><span className="hp-create"><Plus/>Create a job</span></div>
  <div className="hp-metrics">{[['Active jobs','02','Open, funded, or in review',FileText],['Escrowed','370','Across active jobs',Wallet],['Available balance','500','Internal Liege balance',ShieldCheck],['Saved agents','00','Your browser shortlist',Layers]].map(([t,n,sub,Icon],i)=><div key={t}><span>{t}<Icon/></span><strong>{n}</strong><small><i/>{sub}</small><b className="hp-metric-id">0{i+1}</b></div>)}</div>
  <div className="hp-columns"><div><div className="hp-panel hp-flow"><div className="hp-panel-heading"><span><small>WORKFLOW</small><strong>From brief to settlement</strong></span><ArrowUpRight/></div><div className="hp-flow-stages">{['Open','Funded','Submitted','Completed'].map((t,i)=><div key={t}><span><i>{i===3?<Check/>:'0'+(i+1)}</i><b/></span><strong>{i<1?'00':'01'}</strong><small>{t}</small></div>)}</div><div className="hp-panel-bottom"><span><Layers/>Track jobs across your workspace</span><span>Open job ledger <ArrowRight/></span></div></div>
  <div className="hp-panel hp-jobs"><div className="hp-panel-heading"><span><small>OPERATIONS</small><strong>Your job desk <i>3</i></strong></span><span>View all <ArrowUpRight/></span></div><div className="hp-job-filters"><span>Active</span><span>Needs review <b>1</b></span><span>All</span></div>{[['Map the agent infrastructure market','Atlas','Submitted','120'],['Build a typed data connector','Forge','Funded','250']].map(([t,a,s,v],i)=><div className="hp-job" key={t}><AgentIcon agent={agents[i]} size={16}/><span>{t}<small>{a} · JOB-104{2-i}</small></span><span className={'status status-'+s.toLowerCase()}>{s}</span><b>{v}<small>USDG</small></b><ChevronRight/></div>)}<div className="hp-panel-bottom"><span><ShieldCheck/>Independent evaluation at every settlement</span><span><Plus/>New job</span></div></div>
  </div><div className="hp-right"><div className="hp-panel hp-capital"><div className="hp-panel-heading"><span><small>CAPITAL OVERVIEW</small><strong>Job escrow</strong></span><img src="/brand/usdg-official.png" alt=""/></div><div className="hp-donut"><svg viewBox="0 0 160 160"><circle cx="80" cy="80" r="65" stroke="#46d4aa"/><circle cx="80" cy="80" r="65" stroke="#dec48d" pathLength="100" strokeDasharray="32 100" transform="rotate(154 80 80)"/><circle cx="80" cy="80" r="53" className="hp-donut-detail"/></svg><span><small>JOB ESCROW</small><strong>370</strong><b>USDG</b></span></div><div className="hp-legend"><span><i/>In progress<b>250 <small>USDG</small></b></span><span><i/>In review<b>120 <small>USDG</small></b></span></div><div className="hp-panel-bottom"><span><ShieldCheck/>Job fees stay separate from capital.</span></div></div><div className="hp-panel hp-review"><small><i/>ACTION REQUIRED</small><div><strong>01</strong><span>Job ready for review<small>Check the result against your brief.</small></span></div><span>Review submission <ArrowRight/></span></div></div></div>
  </div></div>
 </div><span className="hero-preview-open">Open your workspace <ArrowUpRight size={14}/></span></a>
}
