import React,{useEffect,useRef,useId} from 'react'
import { X, ArrowRight, AlertCircle } from 'lucide-react'
export function Button({children,secondary=false,small=false,href,...props}){const Component=href?'a':'button';return <Component href={href} className={'l-button'+(secondary?' secondary':'')+(small?' small':'')} {...props}>{children}</Component>}
export function Status({value}){return <span className={'status status-'+value.toLowerCase()}><i/>{value}</span>}
export function Empty({title='Nothing here yet',children,action}){return <div className="empty-state"><span className="empty-symbol">◇</span><h3>{title}</h3><p>{children}</p>{action}</div>}
export function Modal({title,children,onClose,wide=false}){const ref=useRef(null),titleId=useId();useEffect(()=>{const before=document.activeElement;ref.current.showModal();ref.current.querySelector('input:not([type=hidden]),textarea,select')?.focus();return()=>before?.focus?.()},[]);return <dialog ref={ref} aria-labelledby={titleId} className={'l-dialog'+(wide?' wide':'')} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="dialog-head"><div><span className="eyebrow">LIEGE WORKSPACE</span><h2 id={titleId}>{title}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>}
export function Field({label,help,error,children}){return <label className="field"><span>{label}</span>{children}{help&&<small>{help}</small>}{error&&<small className="error-text">{error}</small>}</label>}
export function Notice({children,error=false}){return <div className={'l-notice'+(error?' error':'')} role={error?'alert':undefined}><AlertCircle size={15}/><span>{children}</span></div>}
export function SectionHeading({eyebrow,title,children,action}){return <div className="app-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{children&&<p>{children}</p>}</div>{action}</div>}
