import React,{useState} from 'react'
import {ArrowUpRight,ArrowRight,Plus,ChevronRight,ShieldCheck,Wallet,BriefcaseBusiness,Check,Bookmark,Pause,Play,Activity,Clock,SlidersHorizontal,Layers} from 'lucide-react'
import {AgentIcon} from './ProductArt'
import {Button,Status,Empty} from './UI'
import {money} from './data'

function trackPointer(e){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--pointer-x',`${e.clientX-r.left}px`);e.currentTarget.style.setProperty('--pointer-y',`${e.clientY-r.top}px`)}
export function Surface({children,className='',...props}){return <section className={'premium-surface '+className} onPointerMove={trackPointer} {...props}>{children}</section>}
const shortDate=iso=>new Date(iso).toLocaleDateString('en-US',{month:'short',day:'numeric'})
const stageGroups=[['Draft','Prepare','#8f9d96'],['Open','Ready','#c1dc82'],['Funded','In progress','#43d3b3'],['Submitted','In review','#e8c58b'],['Completed','Accepted','#18e299']]
const activityLabel={Draft:'Draft created',Open:'Job opened',Funded:'Escrow funded',Submitted:'Deliverable submitted',Completed:'Result accepted',Rejected:'Result rejected',Challenged:'Result challenged',Expired:'Job expired'}

export default function WorkspaceOverview({state,agents,onCreate,onJob,onAgent,onHire,navigate,onPause,onSaved}){
  const [jobFilter,setJobFilter]=useState('Active'),[activityFilter,setActivityFilter]=useState('All events')
  const active=state.jobs.filter(j=>['Funded','Submitted'].includes(j.status)),review=state.jobs.filter(j=>j.status==='Submitted'),completed=state.jobs.filter(j=>j.status==='Completed')
  const escrow=active.reduce((n,j)=>n+Number(j.budget),0),funded=active.filter(j=>j.status==='Funded').reduce((n,j)=>n+Number(j.budget),0),inReview=escrow-funded
  const filtered=state.jobs.filter(j=>jobFilter==='All'||jobFilter==='Active'&&['Open','Funded','Submitted','Challenged'].includes(j.status)||jobFilter==='Needs review'&&j.status==='Submitted').slice(0,4)
  const events=state.jobs.flatMap(j=>j.history.map((h,i)=>({...h,job:j,key:j.id+'-'+i}))).filter(h=>activityFilter==='All events'||activityFilter==='Evaluations'&&['Submitted','Completed','Rejected','Challenged'].includes(h.status)||activityFilter==='Funding'&&h.status==='Funded').sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,5)
  const metrics=[
    {label:'Active jobs',value:String(active.length).padStart(2,'0'),note:'Funded & in review',Icon:BriefcaseBusiness,action:()=>navigate('jobs'),visual:'bars'},
    {label:'In escrow',value:money(escrow),unit:'USDG',note:'Held across '+active.length+' sample '+(active.length===1?'job':'jobs'),Icon:Wallet,action:()=>navigate('jobs'),visual:'escrow'},
    {label:'Completed jobs',value:String(completed.length).padStart(2,'0'),note:state.jobs.length?`${completed.length} of ${state.jobs.length} total jobs`:'No jobs yet',Icon:ShieldCheck,action:()=>navigate('jobs'),visual:'complete'},
    {label:'Saved agents',value:String(state.saved.length).padStart(2,'0'),note:'Your personal shortlist',Icon:Bookmark,action:onSaved,visual:'agents'}
  ]
  return <div className="overview-premium">
    <div className="overview-heading"><div><span className="eyebrow"><span/> WORKSPACE / OVERVIEW</span><h1>Your work, in motion<span>.</span></h1><p>A clear view of your agents, jobs, and capital.</p></div><div className="overview-heading-actions"><span className="overview-date"><Clock size={12}/>{new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span><div><Button secondary onClick={()=>navigate('agents')}>Explore agents <ArrowUpRight size={14}/></Button><Button onClick={onCreate}><Plus size={15}/>Create a job</Button></div></div></div>
    <div className="premium-metrics">{metrics.map(({label,value,unit,note,Icon,action,visual},i)=><Surface className={'premium-metric metric-'+visual} key={label}><div className="metric-label"><span>{label}</span><Icon size={15}/></div><button className="metric-value" aria-label={label+': '+value+(unit?' '+unit:'')} onClick={action}>{value}<small>{unit}</small><ArrowUpRight size={16}/></button><div className="metric-bottom"><span><i/> {note}</span><span className="metric-number">0{i+1}</span></div><div className="metric-decoration" aria-hidden="true">{Array.from({length:18},(_,n)=><i key={n} style={{height:8+((n*7+i*3)%13)*2+'px',opacity:.1+n*.04}}/>)}</div></Surface>)}</div>
    <div className="overview-columns">
      <div className="overview-primary">
        <Surface className="pipeline-panel"><div className="premium-panel-head"><div><span className="panel-overline">WORKFLOW</span><h2>From brief to settlement</h2></div><a href="/docs/jobs" aria-label="Read about the job lifecycle"><ArrowUpRight size={16}/></a></div><div className="pipeline-stages">{stageGroups.map(([status,label,color],i)=>{const count=state.jobs.filter(j=>j.status===status).length;return <button key={status} onClick={()=>navigate('jobs',status)} className={count?'has-jobs':''} style={{'--stage-color':color}}><span className="pipeline-step"><i>{i===4?<Check size={12}/>:String(i+1).padStart(2,'0')}</i>{i<4&&<b/>}</span><strong>{count.toString().padStart(2,'0')}</strong><span>{status}</span><small>{label}</small></button>})}</div><div className="pipeline-footer"><span><Layers size={12}/>{state.jobs.length} sample jobs across your workspace</span><button onClick={()=>navigate('jobs')}>Open job ledger <ArrowRight size={12}/></button></div></Surface>
        <Surface className="work-ledger"><div className="premium-panel-head"><div><span className="panel-overline">OPERATIONS</span><h2>Your job desk <span>{state.jobs.length}</span></h2></div><button className="subtle-link" onClick={()=>navigate('jobs')}>View all <ArrowUpRight size={14}/></button></div><div className="ledger-toolbar"><div className="segmented-tabs" aria-label="Overview job filter">{['Active','Needs review','All'].map(f=><button key={f} aria-pressed={jobFilter===f} onClick={()=>setJobFilter(f)}>{f}{f==='Needs review'&&<span>{review.length}</span>}</button>)}</div><span className="ledger-count">{filtered.length} shown</span></div><div className="premium-job-list">{filtered.length?filtered.map(j=>{const a=agents.find(a=>a.id===j.agent),index=stageGroups.findIndex(g=>g[0]===j.status);return <button className="premium-job-row" key={j.id} onClick={()=>onJob(j)}><AgentIcon agent={a} size={21}/><span className="premium-job-title"><strong>{j.title}</strong><small>{a?.name||j.agent}<i/> {j.id}</small></span><span className="premium-job-progress"><Status value={j.status}/><span className="job-step-bars" aria-hidden="true">{stageGroups.map((g,i)=><i key={g[0]} className={i<=index?'done':''}/>)}</span></span><span className="premium-job-budget"><b>{money(j.budget)} <small>USDG</small></b><span>Due {shortDate(j.deadline)}</span></span><ChevronRight size={14}/></button>}):<div className="premium-empty"><Check size={20}/><strong>{jobFilter==='Needs review'?'You’re all caught up.':'No jobs in this view.'}</strong><span>{jobFilter==='Needs review'?'New submissions will appear here.':'Create a job or choose another filter.'}</span></div>}</div><div className="ledger-footer"><span><ShieldCheck size={12}/>Independent evaluation at every settlement</span><button onClick={onCreate}><Plus size={13}/>New job</button></div></Surface>
        <Surface className="activity-panel"><div className="premium-panel-head"><div><span className="panel-overline">AUDIT TRAIL</span><h2>Workspace activity</h2></div><select value={activityFilter} onChange={e=>setActivityFilter(e.target.value)} aria-label="Filter activity">{['All events','Evaluations','Funding'].map(f=><option key={f}>{f}</option>)}</select></div><div className="activity-feed">{events.length?events.map(h=><button key={h.key} onClick={()=>onJob(h.job)}><span className={'activity-event-icon event-'+h.status.toLowerCase()}>{h.status==='Completed'?<Check size={14}/>:h.status==='Funded'?<Wallet size={14}/>:<Activity size={14}/>}</span><span><strong>{activityLabel[h.status]||h.status}<i>Simulated</i></strong><small>{h.job.title}</small></span><time dateTime={h.at}>{shortDate(h.at)}<small>{new Date(h.at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false})}</small></time></button>):<div className="premium-empty">No events in this category yet.</div>}</div></Surface>
      </div>
      <div className="overview-secondary">
        <Surface className="escrow-overview"><div className="premium-panel-head"><div><span className="panel-overline">CAPITAL OVERVIEW</span><h2>Job escrow</h2></div><img src="/brand/usdg-official.png" alt="USDG" className="currency-token"/></div><div className="escrow-chart"><svg viewBox="0 0 180 180" aria-label={`${money(escrow)} USDG in sample escrow`} role="img"><circle className="donut-track" cx="90" cy="90" r="73"/>{funded>0&&<circle className="donut-funded" cx="90" cy="90" r="73" pathLength="100" strokeDasharray={`${escrow?funded/escrow*100:0} 100`} transform="rotate(-90 90 90)"/>}{inReview>0&&<circle className="donut-review" cx="90" cy="90" r="73" pathLength="100" strokeDasharray={`${escrow?Math.max(0,inReview/escrow*100-1):0} 100`} strokeDashoffset={escrow?-funded/escrow*100-1:0} transform="rotate(-90 90 90)"/>}<circle className="donut-inner" cx="90" cy="90" r="59"/></svg><div><span>SAMPLE ESCROW</span><strong>{money(escrow)}</strong><small>USDG</small></div></div><div className="escrow-legend"><div><span><i/>In progress</span><b>{money(funded)} <small>USDG</small></b></div><div><span><i/>In review</span><b>{money(inReview)} <small>USDG</small></b></div></div><div className="escrow-note"><ShieldCheck size={13}/><span>Job fees and strategy capital<br/>are tracked separately.</span></div></Surface>
        <Surface className={'review-panel'+(!review.length?' review-clear':'')}><span className="review-indicator"><span/>{review.length?'ACTION REQUIRED':'UP TO DATE'}</span><div><strong>{String(review.length).padStart(2,'0')}</strong><span>{review.length===1?'job ready for review':'jobs ready for review'}<small>{review.length?'Check the result against your brief.':'No submissions are waiting.'}</small></span></div><button onClick={()=>review.length?onJob(review[0]):navigate('jobs')}>{review.length?'Review submission':'View your jobs'}<ArrowRight size={14}/></button></Surface>
        <Surface className="permission-overview"><div className="premium-panel-head"><div><span className="panel-overline">STRATEGY WALLET</span><h2>Your capital. Your rules.</h2></div><span className="permission-emblem"><ShieldCheck size={23}/></span></div><div className="permission-state"><i className={state.policy.paused?'paused':''}/>{state.policy.paused?'Sample execution paused':'Sample permissions active'}</div><div className="permission-cap"><span>Total permission cap</span><strong>{money(state.policy.total)} <small>USDG</small></strong></div><div className="permission-detail"><span>Per trade<b>{money(state.policy.perTrade)} <small>USDG</small></b></span><span>Max. drawdown<b>{state.policy.drawdown}<small>%</small></b></span></div><div className="permission-actions"><button onClick={()=>navigate('wallet')}><SlidersHorizontal size={13}/>Edit limits</button><button onClick={onPause}>{state.policy.paused?<Play size={13}/>:<Pause size={13}/>} {state.policy.paused?'Resume':'Pause'}</button></div></Surface>
      </div>
    </div>
    <div className="agent-discovery-heading"><div><span className="panel-overline">BUILT FOR YOUR NEXT BRIEF</span><h2>A specialist for every job.</h2></div><button onClick={()=>navigate('agents')}>Explore agent market <ArrowRight size={15}/></button></div>
    <div className="discovery-grid">{agents.slice(0,3).map(a=><Surface className="discovery-card" key={a.id} style={{'--agent-color':a.color}}><div className="discovery-top"><AgentIcon agent={a} size={23}/><span>{a.category}</span><button className="icon-button" aria-label={'View '+a.name} onClick={()=>onAgent(a)}><ArrowUpRight size={16}/></button></div><button className="discovery-name" onClick={()=>onAgent(a)}>{a.name}<span>{a.symbol}</span></button><p>{a.description}</p><div className="discovery-bottom"><span>From <b>{money(a.price)}</b> USDG / job</span><button onClick={()=>onHire(a)}>Hire <ArrowRight size={13}/></button></div></Surface>)}</div>
    <div className="overview-footnote"><span><i/>LOCAL SAMPLE WORKSPACE</span><p>All amounts and activity are illustrative. Your drafts are saved in this browser.</p><a href="/docs/status">Product status <ArrowUpRight size={11}/></a></div>
  </div>
}
