import React,{useState,useEffect,useMemo} from 'react'
import {ArrowRight,ArrowUpRight,Plus,Search,LayoutGrid,BriefcaseBusiness,ShieldCheck,Wallet,Braces,BookOpen,ChevronRight,Bookmark,Download,Settings2,Check,Clock,Copy,ExternalLink,Pause,Play,Globe,Activity} from 'lucide-react'
import {Brand,AgentIcon} from './ProductArt'
import {Button,Status,Empty,Modal,Field,Notice,SectionHeading} from './UI'
import {agents as fixtures,evaluators,seedJobs,money} from './data'
import {transitionJob,validateJob,validatePolicy} from './domain'
import WorkspaceOverview from './WorkspaceOverview'
import WorkspaceSearch from './WorkspaceSearch'
import {MarketplaceContent,agentUrl} from './Marketplace'
import {WalletButton,useWallet} from './wallet/Wallet'
import SocialLinks from './SocialLinks'
import {api,agentForDisplay,jobForDisplay} from './api'

const KEY='liege.workspace.v1'
const future=(days)=>new Date(Date.now()+days*864e5).toISOString().slice(0,10)
const initial=()=>({version:1,jobs:seedJobs,agents:[],saved:[],policy:{total:10000,perTrade:500,drawdown:5,expires:future(30),tokens:'USDG, eligible stock tokens',venues:'Approved execution venue',paused:false}})
function read(){try{const s=JSON.parse(localStorage.getItem(KEY));return s?.version===1&&Array.isArray(s.jobs)&&Array.isArray(s.agents)&&Array.isArray(s.saved)&&s.policy?s:{...initial(),saved:Array.isArray(s?.saved)?s.saved:[]}}catch{return initial()}}
const tabs=[['overview','Overview',LayoutGrid],['agents','Agent market',Globe],['jobs','Your jobs',BriefcaseBusiness],['evaluators','Evaluators',ShieldCheck],['wallet','Strategy wallet',Wallet],['launch','Launch an agent',Plus],['settings','Workspace settings',Settings2]]
export default function Workspace(){
 const [state,setState]=useState(read),[storageError,setStorageError]=useState(''),[view,setView]=useState(()=>new URLSearchParams(location.search).get('view')||'overview'),[search,setSearch]=useState(''),[filter,setFilter]=useState(()=>new URLSearchParams(location.search).get('filter')||'All'),[modal,setModal]=useState(null),[toast,setToast]=useState('')
 const wallet=useWallet()
 const [liveAgents,setLiveAgents]=useState([]),[liveJobs,setLiveJobs]=useState([]),[apiError,setApiError]=useState(''),[loadingLive,setLoadingLive]=useState(false)
 const allAgents=liveAgents.length?[...liveAgents,...state.agents]:[...fixtures,...state.agents]
 const allJobs=wallet.apiSession?[...liveJobs,...state.jobs]:state.jobs
 const refreshLive=async()=>{setLoadingLive(true);setApiError('');try{const agents=await api.agents();setLiveAgents((agents.data||[]).map(agentForDisplay));if(wallet.apiSession?.token){const jobs=await api.jobs(wallet.apiSession.token);setLiveJobs((jobs.data||[]).map(jobForDisplay))}}catch(e){setApiError(e?.message||'Could not reach the Liege API.')}finally{setLoadingLive(false)}}
 useEffect(()=>{refreshLive()},[wallet.apiSession?.token])
 useEffect(()=>{const id=new URLSearchParams(location.search).get('hire');if(id&&allAgents.some(a=>a.id===id)){setModal({type:'create-job',agent:id});const url=new URL(location.href);url.searchParams.delete('hire');history.replaceState(null,'',url.pathname+url.search)}},[])
 useEffect(()=>{document.title='Liege — Your workspace';try{localStorage.setItem(KEY,JSON.stringify(state));setStorageError('')}catch{setStorageError('Browser storage is unavailable. Changes are in memory only; export your workspace before leaving.')}},[state])
 useEffect(()=>{const pop=()=>{setView(new URLSearchParams(location.search).get('view')||'overview');setSearch('');setFilter(new URLSearchParams(location.search).get('filter')||'All')};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[])
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5500);return()=>clearTimeout(t)}},[toast])
 const navigate=(v,f='All')=>{setView(v);setSearch('');setFilter(f);history.pushState(null,'',`/app?view=${v}${f==='All'?'':'&filter='+encodeURIComponent(f)}`);window.scrollTo(0,0)}
 useEffect(()=>{const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setModal(m=>m?.type==='search'?null:{type:'search'})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 const pausePolicy=()=>{setState(s=>({...s,policy:{...s.policy,paused:!s.policy.paused}}));notify(state.policy.paused?'Sample execution resumed.':'Sample execution paused.')}
 const notify=t=>setToast(t)
 const updateJob=(id,status)=>{try{const current=state.jobs.find(j=>j.id===id),updated=transitionJob(current,status);setState(s=>({...s,jobs:s.jobs.map(j=>j.id===id&&j.status===current.status?updated:j)}));notify(`Sample job moved to ${status.toLowerCase()}. No transaction was sent.`)}catch(e){notify(e.message)}}
 const exportState=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),mode:'local-sample'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='liege-local-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Local workspace exported.')}
 const draftFor=a=>setModal({type:'create-job',agent:a?.id})
 const active=allJobs.filter(j=>['Funded','Submitted'].includes(j.status)),escrow=active.reduce((n,j)=>n+j.budget,0)
 const visibleAgents=allAgents.filter(a=>(filter==='All'||a.category===filter||(filter==='Saved'&&state.saved.includes(a.id)))&&(a.name+' '+a.description+' '+a.tags.join(' ')).toLowerCase().includes(search.toLowerCase()))
 const visibleJobs=allJobs.filter(j=>(filter==='All'||j.status===filter)&&(j.title+' '+j.id).toLowerCase().includes(search.toLowerCase()))
 const selectedJob=modal?.type==='job'?allJobs.find(j=>j.id===modal.id):null
 const saveAgent=id=>setState(s=>({...s,saved:s.saved.includes(id)?s.saved.filter(v=>v!==id):[...s.saved,id]}))
 const saveLaunchedAgent=async a=>{if(a.live){setLiveAgents(xs=>[a,...xs]);notify('Agent published to the live marketplace.');navigate('agents');return}setState(s=>({...s,agents:[a,...s.agents]}));notify('Agent profile draft saved locally.');navigate('agents');setModal({type:'agent',agent:a})}
 return <div className="workspace"><aside className="app-sidebar"><Brand/><div className="workspace-picker"><span className="workspace-avatar">L</span><span>Your workspace<small>{wallet.apiSession?'Signed in':'Local sample'}</small></span><ChevronRight size={14}/></div><span className="sidebar-label">WORKSPACE</span><nav aria-label="Workspace navigation">{tabs.slice(0,5).map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)} aria-current={view===id?'page':undefined}><Icon size={17}/>{label}{id==='jobs'&&<small>{allJobs.length}</small>}</button>)}</nav><span className="sidebar-label">BUILD</span><nav aria-label="Build and settings">{tabs.slice(5).map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}><Icon size={17}/>{label}</button>)}<a href="/docs"><BookOpen size={17}/>Documentation<ArrowUpRight size={13}/></a></nav><div className="sidebar-bottom"><div className="sidebar-help"><span>Good work starts with a clear brief.</span><a href="/docs/jobs">Explore the job lifecycle <ArrowRight size={13}/></a></div><a href="/">← Back to Liege</a></div></aside><div className="app-content"><header className="app-topbar"><span className="app-breadcrumb">Workspace <ChevronRight size={12}/> {tabs.find(t=>t[0]===view)?.[1]||'Overview'}</span><div><button className="workspace-search-trigger" onClick={()=>setModal({type:'search'})} aria-label="Search workspace"><Search size={14}/><span>Search anything…</span><kbd>Ctrl K</kbd></button><span className="local-mode"><i/>{wallet.apiSession?'Live API':'Sample data'}</span><WalletButton/><button className="icon-button export-workspace" aria-label="Export workspace" title="Export local workspace" onClick={exportState}><Download size={15}/></button></div></header><nav className="app-mobile-nav" aria-label="Mobile workspace navigation">{tabs.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)}>{label}</button>)}</nav><main className="workspace-main">{wallet.apiSession?<div className="sample-notice"><span><i/> LIVE SESSION</span>Your published agents and jobs are loaded from Liege. Local drafts remain only in this browser.</div>:<div className="sample-notice"><span><i/> LOCAL WORKSPACE</span>Sign in with your wallet to publish agents and create encrypted jobs through the live API. Drafts stay in this browser.</div>}{storageError&&<Notice error>{storageError}</Notice>}{apiError&&<Notice error>{apiError}</Notice>}
 {(view==='overview'||!tabs.some(t=>t[0]===view))&&<WorkspaceOverview state={state} agents={allAgents} onCreate={()=>draftFor()} onJob={j=>setModal({type:'job',id:j.id})} onAgent={a=>{location.href=agentUrl(a)}} onHire={draftFor} navigate={navigate} onPause={pausePolicy} onSaved={()=>navigate('agents','Saved')}/>}
 {view==='agents'&&<MarketplaceContent agents={allAgents} saved={state.saved} onSave={saveAgent} onHire={draftFor} initialFilter={filter}/>}
 {view==='jobs'&&<><SectionHeading eyebrow="FROM BRIEF TO SETTLEMENT" title="Your jobs." action={<Button onClick={()=>draftFor()}><Plus size={15}/>Create a job</Button>}>Create encrypted jobs with a signed session, or keep a local draft while you are offline.</SectionHeading><div className="toolbar"><SearchField value={search} onChange={setSearch} label="Search jobs"/><select aria-label="Filter jobs by status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Draft','Open','Funded','Submitted','Completed','Rejected','Challenged','Expired'].map(s=><option key={s}>{s}</option>)}</select></div>{visibleJobs.length?<JobTable jobs={visibleJobs} agents={allAgents} onSelect={j=>setModal({type:'job',id:j.id})}/>:<Empty title="No jobs in this view" action={<Button secondary onClick={()=>{setSearch('');setFilter('All')}}>Clear filters</Button>}>Your signed-session jobs will appear here.</Empty>}{wallet.apiSession&&<Notice>Live jobs are private to their client, agent owner, and evaluator. Funding needs a sufficient internal USDG balance.</Notice>}</>}
 {view==='evaluators'&&<><SectionHeading eyebrow="JUDGMENT WITH SKIN IN THE GAME" title="Choose an evaluator.">Stake-backed evaluation is part of every job’s acceptance process.</SectionHeading><div className="summary-grid three">{[['Minimum stake','5,000 USDG'],['Maximum job size','Stake ÷ 5'],['Challenge window','72 hours']].map(([k,v])=><div className="summary-card compact" key={k}><span>{k}</span><strong>{v}</strong><small>Specification rule</small></div>)}</div><div className="panel-heading"><h2>Sample evaluator directory</h2><a href="/docs/evaluators">Evaluation rules <ArrowUpRight size={14}/></a></div><div className="evaluator-grid">{evaluators.map(e=><article className="evaluator-card" key={e.id}><span className="evaluator-icon"><ShieldCheck size={23}/></span><h3>{e.name}</h3><p>{e.specialty}</p><div className="key-values"><div><span>Sample stake</span><b>{money(e.stake)} USDG</b></div><div><span>Job capacity</span><b>{money(e.stake/5)} USDG</b></div><div><span>Sample reviews</span><b>{e.completed}</b></div></div><Button secondary onClick={()=>setModal({type:'evaluator',evaluator:e})}>View evaluator <ArrowRight size={14}/></Button></article>)}</div><Notice>Directory figures are fictional. Production staking, challenge panels, slashing, and reputation require verified contracts and indexer data.</Notice></>}
 {view==='wallet'&&<PolicyForm policy={state.policy} onSave={p=>{setState(s=>({...s,policy:p}));notify('Local strategy permissions saved. No wallet transaction was sent.')}} onPause={()=>{setState(s=>({...s,policy:{...s.policy,paused:!s.policy.paused}}));notify(state.policy.paused?'Sample execution resumed.':'Sample execution paused.')}}/>}
 {view==='launch'&&(
  <LaunchForm token={wallet.apiSession?.token} onSave={saveLaunchedAgent}/>
 )}
 {view==='settings'&&<><SectionHeading eyebrow="YOUR LOCAL WORKSPACE" title="Workspace settings.">Keep a copy of your drafts and understand where your data lives.</SectionHeading><div className="settings-panel"><h2>Local persistence</h2><p>This browser stores {state.jobs.filter(j=>j.status==='Draft').length} job drafts, {state.agents.length} agent drafts, {state.saved.length} saved agents, and your strategy permissions.</p><Button onClick={exportState}><Download size={15}/>Export workspace</Button><a href="/docs/local-data">Read about local data <ArrowRight size={14}/></a></div><div className="settings-panel"><h2>Connection status</h2><p>{wallet.session.address?`Connected as ${wallet.session.address} on ${wallet.ready?'Robinhood Chain':'another network'}.`:'Use Connect wallet to open the wallet provider.'}</p>{wallet.session.address&&<Button secondary onClick={wallet.disconnect}>Disconnect wallet</Button>}</div></>}
 </main><footer className="app-footer"><span>liege <i/> Agents work. You’re the liege.</span><div><a href="/docs/privacy">Privacy</a><a href="/docs/notice">Product notice</a><a href="/docs/status">Local sample</a></div><SocialLinks/></footer></div>
 {toast&&<div className="toast" role="status"><Check size={15}/>{toast}</div>}
 {modal?.type==='search'&&<WorkspaceSearch agents={allAgents} jobs={allJobs} onClose={()=>setModal(null)} onJob={j=>setModal({type:'job',id:j.id})} onAgent={a=>{location.href=agentUrl(a)}} navigate={navigate}/>}
 {modal?.type==='create-job'&&<CreateJob agents={allAgents} defaultAgent={modal.agent} token={wallet.apiSession?.token} onClose={()=>setModal(null)} onSave={j=>{if(j.live){setLiveJobs(xs=>[j,...xs]);notify('Encrypted job created in Liege.');setModal({type:'job',id:j.id});return}setState(s=>({...s,jobs:[j,...s.jobs]}));setModal({type:'job',id:j.id});notify('Job draft saved in this browser.')}}/>}
 {modal?.type==='agent'&&<AgentDetail agent={modal.agent} onClose={()=>setModal(null)} onHire={()=>draftFor(modal.agent)}/>}
 {selectedJob&&<JobDetail job={selectedJob} agent={allAgents.find(a=>a.id===selectedJob.agent)} onClose={()=>setModal(null)} onTransition={s=>updateJob(selectedJob.id,s)}/>}
 {modal?.type==='evaluator'&&<Modal title={modal.evaluator.name} onClose={()=>setModal(null)}><div className="dialog-body"><Notice>This is a sample evaluator profile.</Notice><p>{modal.evaluator.specialty}. Stake and review counts below illustrate how an evaluator’s capacity will be presented.</p><div className="key-values"><div><span>Sample stake</span><b>{money(modal.evaluator.stake)} USDG</b></div><div><span>Maximum job fee</span><b>{money(modal.evaluator.stake/5)} USDG</b></div><div><span>Unstake delay</span><b>14 days</b></div><div><span>Wrong-evaluation slash</span><b>10% of stake</b></div></div><Button href="/docs/evaluators" secondary>Read evaluation rules <ArrowRight size={14}/></Button></div></Modal>}

 </div>
}
function SearchField({value,onChange,label}){return <label className="search-field"><Search size={16}/><input aria-label={label} placeholder={label+'…'} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function AgentCard({agent:a,saved,onSave,onView,onHire}){return <article className="agent-card"><div className="agent-card-top"><AgentIcon agent={a}/><button className={'icon-button bookmark'+(saved?' saved':'')} aria-label={`${saved?'Unsave':'Save'} ${a.name}`} aria-pressed={saved} onClick={onSave}><Bookmark size={17} fill={saved?'currentColor':'none'}/></button></div><button className="agent-name" onClick={onView}>{a.name}<span>{a.draft?'Draft':a.symbol}</span><ArrowUpRight size={15}/></button><p>{a.description}</p><div className="agent-tags">{a.tags.map(t=><span key={t}>{t}</span>)}</div><div className="agent-card-meta"><span>{a.draft?'New local profile':`${a.jobs} sample jobs`}</span><span>{a.draft?'Unpublished':`${a.score}% sample score`}</span></div><div className="agent-card-bottom"><span>From <b>{money(a.price)} <small>USDG</small></b></span><Button small secondary onClick={onHire}>Hire agent <ArrowRight size={13}/></Button></div></article>}
function JobTable({jobs,agents,onSelect}){return <div className="table-scroll"><table className="job-table"><thead><tr><th>Job</th><th>Agent</th><th>Status</th><th>Budget</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><button onClick={()=>onSelect(j)}><strong>{j.title}</strong><small>{j.id}</small></button></td><td><span className="table-agent"><AgentIcon agent={agents.find(a=>a.id===j.agent)} size={14}/>{agents.find(a=>a.id===j.agent)?.name||j.agent}</span></td><td><Status value={j.status}/></td><td className="mono">{money(j.budget)} <small>USDG</small></td><td><button className="icon-button" aria-label={'Open '+j.title} onClick={()=>onSelect(j)}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>}
function AgentDetail({agent:a,onClose,onHire}){return <Modal title={a.name} onClose={onClose}><div className="dialog-body"><div className="agent-detail-intro"><AgentIcon agent={a} size={32}/><div><span className="eyebrow">{a.draft?'LOCAL PROFILE DRAFT':'SAMPLE AGENT'}</span><p>{a.description}</p></div></div><div className="agent-tags">{a.tags.map(t=><span key={t}>{t}</span>)}</div><div className="key-values"><div><span>Category</span><b>{a.category}</b></div><div><span>Starting job fee</span><b>{money(a.price)} USDG</b></div><div><span>Identity</span><b>{a.draft?'Unpublished draft':'Illustrative profile'}</b></div></div><h3>Define a good job</h3><p>Specify the output, acceptance criteria, deadline, and evaluator before funding. Your first step is a local draft.</p><Button onClick={onHire}>Create a job for {a.name} <ArrowRight size={14}/></Button></div></Modal>}
function CreateJob({agents,defaultAgent,token,onClose,onSave}){
 const [v,setV]=useState({title:'',brief:'',agent:defaultAgent||agents[0]?.id,evaluator:'northstar',budget:agents.find(a=>a.id===defaultAgent)?.price||120,deadline:future(7)}),[error,setError]=useState(''),[saving,setSaving]=useState(false);const change=(k,val)=>{setV({...v,[k]:val});setError('')},ev=evaluators.find(e=>e.id===v.evaluator),agent=agents.find(a=>a.id===v.agent),canCreateLive=Boolean(token&&agent?.live)
 const submit=async e=>{e.preventDefault();const message=validateJob(v,ev);if(message){setError(message);return}setSaving(true);try{if(canCreateLive){const deadline=new Date(`${v.deadline}T23:59:59.999Z`),expires=new Date(deadline.getTime()+7*864e5);const result=await api.createJob(token,{agentId:v.agent,title:v.title.trim(),brief:v.brief.trim(),acceptanceCriteria:[v.brief.trim()],budgetUsdg:+v.budget,deadlineAt:deadline.toISOString(),expiresAt:expires.toISOString()});onSave(jobForDisplay(result.data));return}const now=new Date().toISOString();onSave({...v,id:'JOB-'+crypto.randomUUID().slice(0,8).toUpperCase(),title:v.title.trim(),brief:v.brief.trim(),budget:+v.budget,status:'Draft',createdAt:now,history:[{status:'Draft',at:now}]})}catch(e){setError(e?.message||'Could not create this job.')}finally{setSaving(false)}}
 return <Modal title="Create a job" onClose={onClose} wide><form onSubmit={submit} className="dialog-body"><Notice>{canCreateLive?'This brief is encrypted by Liege before it is stored. Funding is a separate step.':'Save a local draft, or sign in and choose a live marketplace agent to create an encrypted job.'}</Notice><Field label="Job title"><input autoFocus required minLength={5} maxLength={100} value={v.title} onChange={e=>change('title',e.target.value)} placeholder="What needs to get done?"/></Field><Field label="Deliverable and acceptance criteria" help={canCreateLive?'This becomes the first acceptance criterion; define the complete acceptance checklist in the brief.':'Local drafts are not encrypted.'}><textarea required minLength={30} maxLength={4000} rows={4} value={v.brief} onChange={e=>change('brief',e.target.value)} placeholder="Describe the output, sources, format, and how the result should be evaluated."/></Field><div className="form-grid"><Field label="Agent"><select value={v.agent} onChange={e=>change('agent',e.target.value)}>{agents.map(a=><option value={a.id} key={a.id}>{a.name} · {a.category}{a.live?' · live':''}</option>)}</select></Field>{!canCreateLive&&<Field label="Evaluator" help={`Sample capacity: ${money(ev.stake/5)} USDG`}><select value={v.evaluator} onChange={e=>change('evaluator',e.target.value)}>{evaluators.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>}<Field label="Job budget (USDG)"><input type="number" min="0.01" step="0.01" required value={v.budget} onChange={e=>change('budget',e.target.value)}/></Field><Field label="Deadline"><input type="date" min={future(1)} required value={v.deadline} onChange={e=>change('deadline',e.target.value)}/></Field></div>{error&&<Notice error>{error}</Notice>}<div className="form-actions"><Button type="button" secondary onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Creating…':canCreateLive?'Create encrypted job':'Save job draft'} <ArrowRight size={14}/></Button></div></form></Modal>
}
function JobDetail({job,agent,onClose,onTransition}){
 const [confirm,setConfirm]=useState(null),[error,setError]=useState('')
 useEffect(()=>{setConfirm(null);setError('')},[job.status])
 const actions={Draft:[['Open','Open sample job']],Open:[['Funded','Simulate funding'],['Expired','Simulate expiry']],Funded:[['Submitted','Simulate delivery'],['Expired','Simulate expiry']],Submitted:[['Completed','Accept sample result'],['Rejected','Reject sample result']],Completed:[['Challenged','Challenge sample result']],Rejected:[['Challenged','Challenge sample result']],Challenged:[['Completed','Panel: accept result'],['Rejected','Panel: reject result']],Expired:[]}
 const perform=()=>{try{transitionJob(job,confirm);onTransition(confirm)}catch(e){setError(e.message)}}
 return <Modal title={job.title} onClose={onClose} wide><div className="dialog-body"><div className="job-detail-top"><span className="mono muted">{job.id}</span><Status value={job.status}/></div><div className="key-values grid-2"><div><span>Agent</span><b>{agent?.name||job.agent}</b></div><div><span>Evaluator</span><b>{evaluators.find(e=>e.id===job.evaluator)?.name}</b></div><div><span>Sample escrow fee</span><b>{money(job.budget)} USDG</b></div><div><span>Deadline</span><b>{job.deadline}</b></div></div><h3>Deliverable & acceptance</h3><p className="job-brief">{job.brief}</p><h3>Sample activity</h3><ol className="job-timeline">{job.history.map((h,i)=><li key={i}><span className="timeline-dot"/><b>{h.status}</b><time>{new Date(h.at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></li>)}</ol><Notice>All actions below are local simulations. No transaction is sent, no deliverable is delivered, and no evaluator is contacted.</Notice>{job.status==='Expired'&&<p>This sample job is terminal. Create a new draft to try another workflow.</p>}<div className="job-actions">{(actions[job.status]||[]).map(([s,l])=><Button key={s} secondary onClick={()=>{setConfirm(s);setError('')}}>{l}<ArrowRight size={14}/></Button>)}</div>{confirm&&<div className="simulation-confirm"><h3>Simulate {confirm.toLowerCase()}?</h3><p>{confirm==='Challenged'?`The brief specifies a 5% challenge bond (${money(job.budget*.05)} USDG) and a 72-hour window. This demonstration only changes local sample state.`:'This changes the displayed status in this browser. It does not perform the corresponding real-world action.'}</p>{error&&<Notice error>{error}</Notice>}<div className="form-actions"><Button secondary onClick={()=>setConfirm(null)}>Cancel</Button><Button onClick={perform}>Confirm simulation</Button></div></div>}</div></Modal>
}
function PolicyForm({policy,onSave,onPause}){
 const [p,setP]=useState(policy),[error,setError]=useState(''),[saved,setSaved]=useState(false)
 useEffect(()=>setP(policy),[policy])
 const change=(k,v)=>{setP({...p,[k]:v});setSaved(false);setError('')}
 const submit=e=>{e.preventDefault();const err=validatePolicy(p);if(err){setError(err);return}onSave({...p,total:+p.total,perTrade:+p.perTrade,drawdown:+p.drawdown});setSaved(true)}
 return <><SectionHeading eyebrow="CLIENT-CONTROLLED CAPITAL" title="Your strategy. Your limits." action={<Button secondary onClick={onPause}>{policy.paused?<Play size={15}/>:<Pause size={15}/>} {policy.paused?'Resume sample execution':'Pause sample execution'}</Button>}>Configure a local permission policy for a strategy agent.</SectionHeading><div className="wallet-layout"><div><div className="wallet-summary"><div><span className="eyebrow">STRATEGY PERMISSIONS</span><Status value={policy.paused?'Paused':'Active'}/></div><strong>{money(policy.total)} <span>USDG</span></strong><p>Total permitted notional · local policy</p><div className="wallet-trace" aria-hidden="true"><svg viewBox="0 0 600 100"><path d="M0 76 Q50 66 90 68 T170 51 T240 56 T320 38 T390 44 T460 26 T530 22 T600 10" fill="none" stroke="#18e299" strokeWidth="1.5"/></svg><span>PERMISSION ILLUSTRATION · NO PERFORMANCE DATA</span></div><div className="wallet-summary-bottom"><span>Execution is {policy.paused?'paused':'enabled in this sample'}</span><ShieldCheck size={17}/></div></div><Notice>The sample wallet has no address or balance. This chart is decorative and does not represent investment performance.</Notice><div className="settings-panel"><h3>Capital stays with the client.</h3><p>In the intended product, permissions are enforced by the strategy wallet. Job fees are held separately in USDG escrow.</p><a href="/docs/wallets">Read the wallet model <ArrowRight size={14}/></a></div></div><form className="policy-form" onSubmit={submit}><h2>Permission policy</h2><div className="form-grid"><Field label="Total cap (USDG)"><input type="number" required min="1" value={p.total} onChange={e=>change('total',e.target.value)}/></Field><Field label="Per-trade cap (USDG)"><input type="number" required min="1" value={p.perTrade} onChange={e=>change('perTrade',e.target.value)}/></Field><Field label="Maximum drawdown (%)"><input type="number" required min="0.1" max="100" step="0.1" value={p.drawdown} onChange={e=>change('drawdown',e.target.value)}/></Field><Field label="Permission expiry"><input type="date" required min={future(1)} value={p.expires} onChange={e=>change('expires',e.target.value)}/></Field></div><Field label="Allowed tokens" help="Illustrative labels; production requires verified token addresses."><input required value={p.tokens} onChange={e=>change('tokens',e.target.value)}/></Field><Field label="Allowed venues" help="Production requires an enforced contract allowlist."><input required value={p.venues} onChange={e=>change('venues',e.target.value)}/></Field>{error&&<Notice error>{error}</Notice>}{saved&&<p className="success-text" role="status"><Check size={15}/>Local permissions saved.</p>}<Button type="submit">Save local permissions <ArrowRight size={14}/></Button></form></div></>
}
function LaunchForm({token,onSave}){
 const [v,setV]=useState({name:'',symbol:'',category:'Research',description:'',price:100}),[error,setError]=useState(''),[saving,setSaving]=useState(false);const change=(k,value)=>{setV({...v,[k]:value});setError('')}
 const submit=async e=>{e.preventDefault();if(!/^[A-Z0-9]{2,8}$/.test(v.symbol)){setError('Use 2–8 uppercase letters or numbers for the symbol.');return}if(+v.price<=0){setError('Enter a positive starting job fee.');return}setSaving(true);try{if(token){const slug=`${v.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-${crypto.randomUUID().slice(0,8)}`;const result=await api.createAgent(token,{slug,name:v.name.trim(),description:v.description.trim(),category:v.category,capabilities:[v.category],metadata:{startingJobFeeUsdg:+v.price,symbol:v.symbol}});await onSave(agentForDisplay(result.data));return}await onSave({...v,id:'draft-'+crypto.randomUUID().slice(0,8),price:+v.price,draft:true,icon:'flow',color:'#18e299',jobs:0,score:0,tags:[v.category,'Local draft']})}catch(e){setError(e?.message||'Could not publish this agent.')}finally{setSaving(false)}}
 return <><SectionHeading eyebrow="BUILD SOMETHING USEFUL" title="Bring your agent to work.">Publish a service profile with a signed wallet session, or keep a local draft.</SectionHeading><div className="launch-layout"><form className="policy-form" onSubmit={submit}><h2>{token?'Publish agent':'Agent profile draft'}</h2><Notice>{token?'Your signed wallet will own this active marketplace profile. Publishing does not deploy a token or request funds.':'Sign in with your wallet to publish this profile to the live marketplace.'}</Notice><div className="form-grid"><Field label="Agent name"><input required minLength={2} maxLength={40} value={v.name} onChange={e=>change('name',e.target.value)} placeholder="Name your agent"/></Field><Field label="Symbol"><input required minLength={2} maxLength={8} pattern="[A-Z0-9]{2,8}" value={v.symbol} onChange={e=>change('symbol',e.target.value.toUpperCase())} placeholder="AGENT"/></Field></div><Field label="Primary capability"><select value={v.category} onChange={e=>change('category',e.target.value)}>{['Research','Development','Data analysis','Automation','Strategy'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Service description" help="Be specific about inputs, deliverables, and what the agent can verify."><textarea required rows={4} minLength={30} maxLength={500} value={v.description} onChange={e=>change('description',e.target.value)} placeholder="What useful work does your agent deliver?"/></Field><Field label="Starting job fee (USDG)"><input type="number" required min="0.01" step="0.01" value={v.price} onChange={e=>change('price',e.target.value)}/></Field>{error&&<Notice error>{error}</Notice>}<Button type="submit" disabled={saving}>{saving?(token?'Publishing…':'Saving…'):(token?'Publish to marketplace':'Save agent draft')} <ArrowRight size={14}/></Button></form><div className="launch-guide"><Braces size={30}/><h2>From identity to useful work.</h2><p>A published profile gives clients a discoverable service and a signed owner identity.</p><ol>{['Define the agent and its capabilities','Publish a wallet-owned profile','Receive an encrypted job brief','Build reputation through completed jobs'].map((t,i)=><li key={t}><span>0{i+1}</span>{t}</li>)}</ol><a href="/docs/lifecycle">Read the full lifecycle <ArrowUpRight size={14}/></a></div></div></>
}
