import test from 'node:test'
import assert from 'node:assert/strict'
import {ROBINHOOD,providerKind,connectWallet,switchToRobinhood,publicAppUrl,mobileWalletLink,walletError,firstAccount,discoverWallets} from '../src/wallet/core.js'
const address='0x1111111111111111111111111111111111111111'
function mock({chain='0x1',unknown=false,reject=false,unsupported=false,stayWrong=false}={}){
 const calls=[]
 return {calls,request:async({method,params})=>{calls.push({method,params});if(method==='eth_requestAccounts'){if(reject)throw {code:4001};return[address]}if(method==='eth_accounts')return[address];if(method==='eth_chainId')return chain;if(method==='wallet_switchEthereumChain'){if(unsupported)throw{code:4200};if(unknown)throw{code:4902};if(!stayWrong)chain=params[0].chainId;return null}if(method==='wallet_addEthereumChain'){unknown=false;return null}throw Error('Unexpected method '+method)}}
}
test('wallet identity distinguishes Phantom even when it also exposes isMetaMask',()=>{assert.equal(providerKind({request(){},isPhantom:true,isMetaMask:true}),'phantom');assert.equal(providerKind({request(){},isMetaMask:true},'io.metamask'),'metamask');assert.equal(providerKind({request(){},isMetaMask:true},'com.other.wallet'),null)})
test('discovery handles late announcements and cleans up listeners',()=>{const target=new EventTarget();const found=[];const stop=discoverWallets(target,(...a)=>found.push(a));const provider=mock();target.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{rdns:'io.metamask'},provider}}));assert.equal(found[0][0],'metamask');assert.equal(found[0][1],provider);stop();target.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{rdns:'app.phantom'},provider}}));assert.equal(found.length,1)})
test('MetaMask adds an unknown network using official configuration, then verifies the selected chain',async()=>{const p=mock({unknown:true});const result=await connectWallet(p,'metamask');assert.equal(result.chain,ROBINHOOD.chainId);assert.deepEqual(p.calls.find(x=>x.method==='wallet_addEthereumChain').params,[ROBINHOOD]);assert.equal(p.calls.filter(x=>x.method==='wallet_switchEthereumChain').length,2)})
test('already selected network does not trigger a switch',async()=>{const p=mock({chain:ROBINHOOD.chainId});assert.equal((await connectWallet(p,'phantom')).address,address);assert.ok(!p.calls.some(x=>x.method.includes('switch')||x.method.includes('addEthereum')))})
test('a rejected account request never prompts for network changes',async()=>{const p=mock({reject:true});await assert.rejects(connectWallet(p,'metamask'),e=>e.code===4001);assert.equal(p.calls.length,1)})
test('Phantom never receives an unsupported custom-network addition',async()=>{const p=mock({unknown:true});await assert.rejects(connectWallet(p,'phantom'),e=>e.code===4902);assert.ok(!p.calls.some(x=>x.method==='wallet_addEthereumChain'));assert.match(walletError({code:4902},'phantom'),/Active Networks/)})
test('a fulfilled switch with the wrong actual network is not reported as connected',async()=>{const p=mock({stayWrong:true});await assert.rejects(switchToRobinhood(p,'metamask'),e=>/still on another/.test(e.userMessage))})
test('cancellation prevents a late approval from initiating network requests',async()=>{const controller=new AbortController();let resolve;const calls=[];const p={request:({method})=>{calls.push(method);return new Promise(r=>{resolve=r})}};const result=connectWallet(p,'metamask',controller.signal);controller.abort();resolve([address]);await assert.rejects(result,e=>e.name==='AbortError');assert.deepEqual(calls,['eth_requestAccounts'])})
test('only valid Ethereum accounts are accepted',()=>{assert.equal(firstAccount(['solana-address']),null);assert.equal(firstAccount([address]),address);assert.equal(firstAccount(null),null)})
test('cancelled and pending errors have actionable messages',()=>{assert.match(walletError({code:4001},'metamask'),/cancelled/);assert.match(walletError({code:-32002},'phantom'),/already waiting/);assert.match(walletError({data:{originalError:{code:4902}}},'phantom'),/Active Networks/)})
test('mobile handoff rejects local addresses and strips unrelated query data',()=>{for(const url of ['http://127.0.0.1:4173','https://localhost','https://192.168.0.1','https://127.0.0.1','https://user:pass@example.com','https://[::1]'])assert.equal(publicAppUrl('',url),null);assert.equal(publicAppUrl('https://liege.example.org','http://localhost:5173/app?token=secret#hash'),'https://liege.example.org/app');assert.equal(publicAppUrl('','https://liege.example.org/marketplace/atlas?query=private'),'https://liege.example.org/marketplace/atlas')})
test('phone links use official browse entry points and restore the wallet picker',()=>{const app='https://liege.example.org/marketplace/atlas';const phantom=new URL(mobileWalletLink('phantom',app));assert.equal(phantom.origin,'https://phantom.app');assert.equal(decodeURIComponent(phantom.pathname.slice('/ul/browse/'.length)),app+'?wallet=phantom');assert.equal(mobileWalletLink('metamask',app),'https://link.metamask.io/dapp/liege.example.org/marketplace/atlas?wallet=metamask');assert.equal(mobileWalletLink('metamask',null),null)})
