import { StyleSheet } from "react-native";
export const C = {
  bg: "#080B0A",
  panel: "#121715",
  raised: "#1B221F",
  border: "#25302A",
  text: "#F1F6F2",
  muted: "#98A69E",
  dim: "#56665C",
  green: "#5BEBA0",
  amber: "#E5C47A",
  red: "#F38D8D",
};
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  flex: { flex: 1 },
  grow: { flex: 1 },
  inline: { flexDirection: "row", alignItems: "center", gap: 9 },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  topbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 14,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 7 },
  brandIcon: { width: 38, height: 38 },
  wordmark: { color: C.text, fontSize: 30, fontWeight: "700", letterSpacing: -1.5 },
  circle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.border,
    justifyContent: "center",
    alignItems: "center",
  },
  avatar: {
    width: 44,
    height: 44,
    backgroundColor: "#173426",
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  notificationDot: {
    position: "absolute",
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: C.green,
    right: 9,
    top: 9,
    borderWidth: 2,
    borderColor: C.bg,
  },
  main: { padding: 24, paddingTop: 23 },
  eyebrow: { color: C.green, fontSize: 10, letterSpacing: 1.7, fontWeight: "600", lineHeight: 18 },
  title: {
    color: C.text,
    fontSize: 36,
    fontWeight: "600",
    letterSpacing: -1.7,
    lineHeight: 43,
    marginTop: 10,
    marginBottom: 22,
  },
  subtitle: { color: C.muted, fontSize: 14, marginTop: 8, marginBottom: 27, lineHeight: 21 },
  body: { color: C.muted, fontSize: 14, lineHeight: 23, marginVertical: 14 },
  small: { color: C.text, fontSize: 12 },
  smallMuted: { color: C.muted, fontSize: 12 },
  tiny: { color: C.muted, fontSize: 9, letterSpacing: 1.5, fontWeight: "600" },
  centerText: { textAlign: "center" },
  heroCard: {
    backgroundColor: C.green,
    padding: 24,
    borderRadius: 28,
    overflow: "hidden",
    minHeight: 234,
  },
  heroEyebrow: { color: "#16442B", fontWeight: "600", fontSize: 10, letterSpacing: 1.4 },
  heroNumber: {
    color: C.bg,
    fontSize: 78,
    fontWeight: "500",
    letterSpacing: -5,
    marginTop: 18,
    lineHeight: 85,
  },
  heroLabel: { color: "#133722", fontSize: 20, fontWeight: "500", letterSpacing: -0.4 },
  heroArrow: {
    backgroundColor: "#0A372017",
    borderRadius: 23,
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  heroFoot: { color: "#205439", fontSize: 10, marginTop: 9 },
  heroRing: {
    width: 230,
    height: 230,
    borderWidth: 1,
    borderColor: "#16452B25",
    borderRadius: 115,
    position: "absolute",
    right: -43,
    top: -35,
  },
  heroRingSmall: {
    width: 190,
    height: 190,
    borderWidth: 1,
    borderColor: "#16452B20",
    borderRadius: 95,
    position: "absolute",
    right: -23,
    top: -15,
  },
  cardLogo: {
    position: "absolute",
    width: 175,
    height: 175,
    right: -10,
    top: -5,
    opacity: 0.35,
    transform: [{ rotate: "-15deg" }],
  },
  metricRow: { flexDirection: "row", gap: 12, marginTop: 12 },
  metric: {
    flex: 1,
    padding: 19,
    backgroundColor: C.panel,
    borderRadius: 22,
    borderColor: C.border,
    borderWidth: 1,
  },
  metricNumber: { color: C.text, fontSize: 28, letterSpacing: -1 },
  metricLabel: { color: C.muted, fontSize: 12, marginTop: 17 },
  attention: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#30533E",
    borderRadius: 22,
    padding: 17,
    backgroundColor: "#101D15",
  },
  attentionIcon: { width: 36, alignItems: "center" },
  sectionHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 30,
    marginBottom: 16,
  },
  sectionTitle: { color: C.text, fontSize: 18, fontWeight: "600", letterSpacing: -0.4 },
  link: { color: C.green, fontSize: 12, fontWeight: "500" },
  list: {
    backgroundColor: C.panel,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#202A24",
  },
  jobRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
  },
  jobIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    backgroundColor: "#20352A",
    justifyContent: "center",
    alignItems: "center",
  },
  rowTitle: { color: C.text, fontSize: 14, fontWeight: "500", lineHeight: 20 },
  rowMeta: { color: C.muted, fontSize: 11, marginTop: 5, lineHeight: 17 },
  amount: { color: C.text, fontSize: 14, fontWeight: "600", lineHeight: 18 },
  assetIcon: { width: 18, height: 18, marginTop: 4, opacity: 0.9 },
  amountDetail: { alignItems: "flex-end", flexDirection: "row", gap: 6 },
  badge: {
    flexDirection: "row",
    gap: 5,
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 7,
  },
  badgeText: { fontSize: 9, fontWeight: "500" },
  dot: { height: 5, width: 5, borderRadius: 3, backgroundColor: C.green },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
  },
  activityDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.raised,
    alignItems: "center",
    justifyContent: "center",
  },
  dockWrap: { backgroundColor: C.bg, paddingHorizontal: 18, paddingTop: 8 },
  dock: {
    flexDirection: "row",
    padding: 6,
    backgroundColor: "#161D19",
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 30,
    marginBottom: 8,
  },
  dockItem: {
    flex: 1,
    minHeight: 58,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  dockSelected: { backgroundColor: C.green },
  dockLabel: { color: C.muted, fontSize: 10, fontWeight: "500" },
  dockBadge: {
    position: "absolute",
    right: 14,
    top: 6,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: "#263F30",
    alignItems: "center",
    justifyContent: "center",
  },
  dockBadgeText: { color: C.green, fontSize: 8, fontWeight: "700" },
  search: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: C.panel,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 17,
    paddingHorizontal: 16,
    minHeight: 52,
    marginBottom: 17,
  },
  searchInput: { flex: 1, color: C.text, fontSize: 14, paddingVertical: 14 },
  filters: { flexDirection: "row", gap: 8, marginBottom: 22 },
  filter: {
    backgroundColor: C.panel,
    paddingVertical: 11,
    paddingHorizontal: 21,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.border,
  },
  filterActive: { backgroundColor: C.green, borderColor: C.green },
  filterText: { color: C.muted, fontSize: 12, fontWeight: "500" },
  results: { color: C.dim, fontWeight: "600", fontSize: 9, letterSpacing: 1.2, marginBottom: 13 },
  proposalCard: {
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    borderRadius: 25,
    padding: 22,
    marginBottom: 14,
  },
  cardTitle: { color: C.text, fontSize: 19, fontWeight: "500", letterSpacing: -0.4 },
  proposalFooter: {
    borderTopWidth: 1,
    borderColor: C.border,
    paddingTop: 17,
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  empty: {
    padding: 28,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.panel,
    alignItems: "center",
  },
  emptyIcon: {
    width: 66,
    height: 66,
    borderRadius: 24,
    backgroundColor: "#1B2C22",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  endMark: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 33,
    marginBottom: 4,
  },
  endLine: { height: 1, width: 44, backgroundColor: C.border },
  endLogo: { height: 24, width: 24, opacity: 0.4 },
  button: {
    backgroundColor: C.green,
    minHeight: 56,
    borderRadius: 19,
    paddingHorizontal: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 15,
  },
  buttonText: { color: C.bg, fontSize: 15, fontWeight: "600" },
  secondary: { backgroundColor: C.raised, borderColor: C.border, borderWidth: 1 },
  overlay: { flex: 1, backgroundColor: "#000000CC", justifyContent: "center", padding: 24 },
  feedback: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: C.panel,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 30,
    padding: 26,
  },
  feedbackIcon: {
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 22,
  },
  modalTitle: {
    color: C.text,
    fontSize: 25,
    fontWeight: "600",
    letterSpacing: -0.7,
    textAlign: "center",
  },
  sheetOverlay: { flex: 1, backgroundColor: "#000000B8", justifyContent: "flex-end" },
  backdrop: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  sheet: {
    backgroundColor: C.panel,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: "90%",
    borderWidth: 1,
    borderColor: C.border,
  },
  handle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.dim,
    alignSelf: "center",
    marginTop: 12,
  },
  sheetContent: { padding: 27, paddingTop: 17 },
  sheetClose: {
    alignSelf: "flex-end",
    marginRight: 18,
    marginTop: 8,
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: C.raised,
  },
  sheetIcon: {
    width: 62,
    height: 62,
    borderRadius: 21,
    backgroundColor: "#203529",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 23,
  },
  sheetTitle: {
    color: C.text,
    fontSize: 29,
    lineHeight: 36,
    letterSpacing: -1,
    marginTop: 8,
    marginBottom: 18,
    fontWeight: "500",
  },
  details: { marginVertical: 22, borderTopWidth: 1, borderColor: C.border },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: C.border,
  },
  detailValue: { color: C.text, fontSize: 12, flexShrink: 1, textAlign: "right" },
  webLink: { flexDirection: "row", gap: 9, paddingVertical: 16, marginBottom: 16 },
  signOut: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    paddingTop: 27,
    paddingBottom: 10,
  },
  onboarding: { flexGrow: 1, padding: 26, paddingTop: 0 },
  tag: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    borderRadius: 20,
    backgroundColor: C.panel,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  orbit: {
    height: 275,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 18,
  },
  orbitOuter: {
    position: "absolute",
    height: 270,
    width: 270,
    borderRadius: 135,
    borderWidth: 1,
    borderColor: "#223B2C",
    backgroundColor: "#0D1711",
  },
  orbitInner: {
    position: "absolute",
    height: 216,
    width: 216,
    borderRadius: 108,
    borderWidth: 1,
    borderColor: "#294A34",
    backgroundColor: "#14281B",
  },
  heroLogo: { height: 228, width: 228, transform: [{ rotate: "-12deg" }] },
  orbitLabel: {
    position: "absolute",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    backgroundColor: "#17241D",
    borderWidth: 1,
    borderColor: "#2C4935",
    borderRadius: 18,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  welcomeTitle: {
    color: C.text,
    fontSize: 40,
    lineHeight: 47,
    letterSpacing: -1.8,
    fontWeight: "600",
    marginTop: 12,
  },
  onboardFeatures: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 10,
    marginBottom: 28,
  },
  feature: { gap: 10, flex: 1 },
  featureText: { color: C.muted, fontSize: 10, lineHeight: 15 },
  footerNote: {
    color: C.muted,
    fontSize: 10,
    lineHeight: 17,
    textAlign: "center",
    marginVertical: 16,
  },
  backButton: { flexDirection: "row", gap: 10, alignItems: "center", marginTop: 15, minHeight: 44 },
  pairSymbol: {
    height: 76,
    width: 76,
    borderRadius: 27,
    backgroundColor: "#1A3022",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 28,
  },
  codeLabel: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 15,
  },
  codeWrap: { position: "relative", marginBottom: 30 },
  codeCells: { flexDirection: "row", gap: 4, alignItems: "flex-start" },
  codeCell: {
    flex: 1,
    aspectRatio: 1,
    backgroundColor: C.panel,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  codeCellActive: { borderColor: C.green, backgroundColor: "#152A1D" },
  codeDigit: { color: C.text, fontSize: 23, fontWeight: "500" },
  hiddenInput: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.015,
    color: "transparent",
  },
  hint: { color: C.muted, fontSize: 11, marginTop: 14, marginBottom: 30 },
  securityNote: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7 },
  splash: { flex: 1, backgroundColor: C.bg, justifyContent: "center", alignItems: "center" },
  splashLogo: { width: 135, height: 135, marginBottom: 10 },
});
