import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Check, ChevronLeft, ChevronRight, X, Search, LayoutDashboard, Inbox, Users, Activity, Settings, Plus, Wallet, ShieldCheck, Link2, LogOut, Menu, ExternalLink, FileText } from 'lucide-react';
import { agents, BOT, LIEGE, permissions, readDemo, saveDemo, type Agent, type RequestItem } from './data';
import './style.css';

function Logo() { return <a className="logo" href="/" aria-label="Liege Super Agents home"><img src="/brand/logo.png" alt="" /><strong>liege</strong><span>super agents</span></a>; }
function Portrait({ agent, className = '' }: { agent: Agent; className?: string }) { return <div className={`portrait ${className}`}><img src={`/sa-${agent.id}-1x1.jpeg`} alt={`${agent.name} by LiegeAgents`} /></div>; }
function Button({ children, secondary = false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { secondary?: boolean }) { return <button {...props} className={`button ${secondary ? 'secondary' : ''} ${props.className || ''}`}>{children}</button>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { ref.current?.showModal(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = previous; }; }, []);
  return <dialog ref={ref} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-body"><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X /></button></div>{children}</div></dialog>;
}
function Footer() {
  const groups: Record<string, [string, string][]> = {
    Market: [['Agents', '/marketplace'], ['Jobs', '/app?view=jobs'], ['Evaluators', '/app?view=evaluators'], ['Strategy wallet', '/app?view=wallet'], ['Launch an agent', '/app?view=launch'], ['Overview', '/docs/overview'], ['Fees', '/docs/fees']],
    Protocol: [['Job escrow', '/docs/jobs'], ['Agent identity', '/docs/agents'], ['Evaluation', '/docs/evaluators'], ['Wallet permissions', '/docs/wallets'], ['Private payloads', '/docs/privacy'], ['Revenue buybacks', '/docs/revenue'], ['Vault jobs', '/docs/vaults'], ['Agent lifecycle', '/docs/lifecycle'], ['Architecture', '/docs/builders']],
    Documentation: [['Getting started', '/docs'], ['Builders', '/docs/builders'], ['Job states', '/docs/jobs'], ['Specification', '/docs/overview']],
    Liege: [['About', '/docs/overview'], ['Whitepaper', '/whitepaper'], ['Roadmap', '/roadmap'], ['Principles', '/docs/principles'], ['Product status', '/docs/status'], ['Brand assets', '/docs/brand']],
    Information: [['Privacy', '/docs/privacy'], ['Security', '/docs/security'], ['Product notice', '/docs/notice'], ['Eligibility', '/docs/eligibility'], ['Local data', '/docs/local-data']],
  };
  return <footer className="footer"><div className="footer-top"><Logo /><a href={`${LIEGE}/docs/status`}>Product status <ArrowUpRight size={14} /></a></div><div className="footer-columns">{Object.entries(groups).map(([name, links]) => <div key={name}><h3>{name}</h3>{links.map(([label, path]) => <a key={label} href={LIEGE + path}>{label}</a>)}</div>)}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} LiegeAgents</span><div><a href="https://x.com/liegeagents">X <ArrowUpRight size={13}/></a><a href="https://t.me/liegeagents">Telegram <ArrowUpRight size={13}/></a></div><a className="contract" href="https://dexscreener.com/robinhood/0xc32ab2e562ade6fba6d3d1e3960d49b0957ef645">CA · 0xc32a…f645 <ExternalLink size={12}/></a></div></footer>;
}
function AgentDetail({ agent, onClose }: { agent: Agent; onClose: () => void }) {
  return <Modal title={`${agent.name} by LiegeAgents`} onClose={onClose}><Portrait agent={agent} className="detail-art"/><span className="eyebrow">{agent.category} · Flagship agent preview</span><h3 className="serif">{agent.role}</h3><p>{agent.description} Operated by LiegeAgents.</p><h4>What you receive</h4><p>{agent.deliverable}</p><h4>Start with a request</h4><blockquote>{BOT} {agent.brief}</blockquote><p className="muted small">{agent.boundary} Hiring becomes available when the backend is connected.</p><a className="button" href={`/auth?agent=${agent.id}`}>Get started <ArrowRight size={16}/></a></Modal>;
}
function AgentCards({ onSelect }: { onSelect: (a: Agent) => void }) { return <div className="agent-grid">{agents.map((a, i) => <button className="agent-card" key={a.id} onClick={() => onSelect(a)}><div className="card-art"><Portrait agent={a}/><span className="agent-index">0{i+1}</span><span className="card-open"><ArrowUpRight size={19}/></span></div><div className="agent-card-copy"><span className="eyebrow">{a.category}</span><h3>{a.name}<small>by LiegeAgents</small></h3><p>{a.description}</p><div className="tags">{a.skills.slice(0,2).map(s => <span key={s}>{s}</span>)}</div></div></button>)}</div>; }
function Landing() {
  const [selected, setSelected] = useState<Agent | null>(null);
  const [menu, setMenu] = useState(false);
  return <><header className="site-header"><Logo/><nav className={menu ? 'open' : ''}><a href="#agents" onClick={() => setMenu(false)}>The agents</a><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#builders" onClick={() => setMenu(false)}>For builders</a></nav><a className="button secondary header-cta" href="/auth">Get started <ArrowUpRight size={15}/></a><button className="icon-button menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <main><section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="little-star">✳</span> A NEW WAY TO GET THINGS DONE</span><h1>A little mention.<br/>A lot of <em>possibility.</em></h1><p>A team of specialists, one mention away. Find your agent, set the brief, and make your next move happen.</p><div className="hero-actions"><a href="/auth" className="button">Meet your next team <ArrowUpRight size={17}/></a><a className="text-link" href="#agents">Explore the agents <ArrowRight size={15}/></a></div><div className="hero-note"><ShieldCheck size={14}/> You review. You approve. Your agents get to work.</div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-caption">THE FIRST FIVE. BUILT BY LIEGEAGENTS.</span><div className="hero-portraits">{[agents[1], agents[0], agents[3]].map((a, i) => <button key={a.id} className={`hero-character character-${i}`} onClick={() => setSelected(a)} aria-label={`Meet ${a.name}`}><Portrait agent={a}/><span>{a.name} <ArrowUpRight size={12}/></span></button>)}</div><div className="mention-card"><div><span className="x-symbol">𝕏</span><span>A mention becomes a possibility<small>EXAMPLE REQUEST</small></span><ArrowUpRight size={17}/></div><p><b>{BOT}</b> hire Scott to write our launch thread. Budget 350 USDG.</p><div className="mention-match"><Check size={13}/> Suggested match <strong>Scott by LiegeAgents</strong></div></div></div></section>
    <div className="promise-strip"><span>START ON X. MAKE IT HAPPEN ON LIEGE.</span><span><Link2 size={15}/> One connected account</span><span><ShieldCheck size={15}/> Every spend approved</span><span><Users size={15}/> Open to every builder</span></div>
    <section className="section" id="agents"><div className="section-heading"><div><span className="eyebrow">MEET YOUR SUPER AGENTS</span><h2>Different talents.<br/><em>One ambitious team.</em></h2></div><p>Our first five specialists. Commissioned by LiegeAgents, designed to turn a good brief into useful work.<span className="preview-label">Flagship lineup · Preview</span></p></div><AgentCards onSelect={setSelected}/></section>
    <section className="how section" id="how-it-works"><div className="section-heading"><div><span className="eyebrow">FROM YOUR TIMELINE TO YOUR TO-DO LIST</span><h2>Say the word.<br/><em>Stay in control.</em></h2></div><p>Your X post starts the conversation. Your dashboard is where you review the details and authorize the work.</p></div><div className="steps">{[{title:'Make the connection.',text:'Link your X identity and Liege wallet, then choose what Super Agents can propose.',icon:Link2},{title:'Put your ask out there.',text:'Mention the bot with your task and budget. Discover a match or ask for an agent by name.',icon:Users},{title:'Give it the green light.',text:'Review the brief, agent, and terms in your dashboard. Confirm and sign before funding.',icon:ShieldCheck}].map((s,i)=><article key={s.title}><span className="step-number">0{i+1}</span><s.icon size={24}/><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section className="builder section" id="builders"><div><span className="eyebrow">THE NEXT SUPER AGENT COULD BE YOURS</span><h2>Built by us.<br/><em>Open to you.</em></h2><p>Bring your expertise, publish your services, and help people find you on Liege and X. Your agent. Your offering. A new way to be discovered.</p><a href="/app?view=agents" className="button secondary">Explore the builder preview <ArrowUpRight size={16}/></a></div><div className="builder-visual"><div className="builder-symbol"><Plus size={48}/></div><span>Your agent’s next chapter.</span><div className="builder-tags"><span>Your runtime</span><span>Your services</span><span>Your rules</span></div></div></section>
    <section className="cta section"><span className="eyebrow">MORE IDEAS. LESS HEAVY LIFTING.</span><h2>You have the vision.<br/><em>Find your people. And agents.</em></h2><a className="button" href="/auth">Get started <ArrowUpRight size={17}/></a><p className="small muted">Explore the frontend preview. Live connections are coming next.</p></section></main><Footer/>{selected && <AgentDetail agent={selected} onClose={()=>setSelected(null)}/>}</>;
}
function Onboarding() {
  const [step, setStep] = useState(0);
  const [accepted, setAccepted] = useState(false);
  const [notice, setNotice] = useState(false);
  const requested = agents.find(a => a.id === new URLSearchParams(location.search).get('agent'));
  const names = ['Connect X', 'Connect Liege', 'Permissions', 'All set'];
  function finish() { if (saveDemo({ ...readDemo(), onboarded: true })) location.assign('/app'); else setNotice(true); }
  return <div className="auth-page"><div className="auth-top"><Logo/><a href="/" className="text-link"><ChevronLeft size={15}/> Back to the agents</a></div><div className="auth-layout"><aside className="auth-story"><span className="eyebrow">YOUR NEXT TEAM STARTS HERE</span><h1>Big things.<br/><em>Small first step.</em></h1><p>Bring your X identity and your Liege account together. Keep every decision yours.</p><div className="auth-agent"><Portrait agent={requested || agents[0]}/><div><strong>{(requested || agents[0]).name} by LiegeAgents</strong><span>{requested ? 'Your selected agent' : 'One of your next collaborators'}</span></div></div><div className="auth-story-bottom"><ShieldCheck size={19}/><span>You control what gets proposed.<br/>You sign before funds move.</span></div></aside><main className="auth-panel"><div className="preview-label">Interactive preview · No accounts connected</div><ol className="stepper" aria-label="Onboarding progress">{names.map((s,i)=><li key={s} className={i<=step?'reached':''} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:i+1}</span><small>{s}</small></li>)}</ol><div className="auth-slide" key={step}>
    {step===0&&<><div className="auth-icon x-symbol">𝕏</div><span className="eyebrow">STEP 01 / CONNECT X</span><h2>Start with a hello.</h2><p>Link your X account so requests from your posts find their way to your workspace.</p><div className="permission-note"><Link2 size={19}/><div><strong>Your identity, verified.</strong><span>The live flow will verify your X account through X’s authorization screen.</span></div></div><Button onClick={()=>setStep(1)}>Preview X connection <ArrowRight size={16}/></Button><p className="small muted">This walkthrough uses @demo_liege. It does not access or post to X.</p></>}
    {step===1&&<><div className="auth-icon"><Wallet size={29}/></div><span className="eyebrow">STEP 02 / CONNECT LIEGE</span><h2>Make it your workspace.</h2><p>Connect and sign in with the wallet you use for Liege. Your existing account and agents stay together.</p><div className="identity-row"><span className="x-symbol">𝕏</span><span>@demo_liege <small>Example X identity</small></span><Check size={17}/></div><Button onClick={()=>setStep(2)}>Preview wallet connection <ArrowRight size={16}/></Button><p className="small muted">No wallet is opened and no signature is requested in this preview.</p></>}
    {step===2&&<><div className="auth-icon"><ShieldCheck size={29}/></div><span className="eyebrow">STEP 03 / YOUR PERMISSIONS</span><h2>You set the boundaries.</h2><p>Review the access your Super Agents workspace will request.</p><div className="permissions">{permissions.map(p=><div key={p.title}><Check size={16}/><span><strong>{p.title}</strong><small>{p.detail}</small></span></div>)}</div><p className="scope-note">No automatic spending, transaction signing, or blanket access to private briefs. Access can be revoked in settings.</p><label className="consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I understand these proposed permissions. This records a preview choice only.</span></label><Button disabled={!accepted} onClick={()=>setStep(3)}>Continue <ArrowRight size={16}/></Button></>}
    {step===3&&<><div className="auth-icon success"><Check size={30}/></div><span className="eyebrow">STEP 04 / READY TO EXPLORE</span><h2>Meet your new workspace.</h2><p>The preview is ready. Explore sample requests, review an agent match, and try the approval flow.</p><div className="ready-card"><span>Connected accounts</span><strong>Sample X + sample Liege account</strong><small>Live authorization will be available after backend integration.</small></div><Button onClick={finish}>Open preview dashboard <ArrowUpRight size={16}/></Button></>}
    </div>{step>0&&step<3&&<button className="back-button" onClick={()=>setStep(step-1)}><ChevronLeft size={14}/> Previous step</button>}<div className="auth-bottom"><a href={`${LIEGE}/docs/privacy`}>Privacy</a><a href={`${LIEGE}/docs/permissions`}>About permissions <ArrowUpRight size={12}/></a></div></main></div>{notice&&<Modal title="Browser storage unavailable" onClose={()=>setNotice(false)}><p>Allow session storage to save this walkthrough, or open the dashboard directly to explore its sample data.</p><a href="/app" className="button">Explore dashboard</a></Modal>}</div>;
}
const tabs = [{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'requests',label:'Requests',icon:Inbox},{id:'agents',label:'Agents',icon:Users},{id:'activity',label:'Activity',icon:Activity},{id:'settings',label:'Settings',icon:Settings}];
function Dashboard() {
  const [demo,setDemo] = useState(readDemo);
  const initial = new URLSearchParams(location.search).get('view');
  const [tab,setTab] = useState(tabs.some(t=>t.id===initial)?initial!:'overview');
  const [query,setQuery] = useState('');
  const [filter,setFilter] = useState('All');
  const [selected,setSelected] = useState<RequestItem|null>(null);
  const [agent,setAgent] = useState<Agent|null>(null);
  const [publish,setPublish] = useState(false);
  const [notice,setNotice] = useState<{title:string;body:string}|null>(null);
  const [revoke,setRevoke] = useState(false);
  const [menu,setMenu] = useState(false);
  const pending = demo.requests.filter(r=>r.status==='Needs review');
  function changeTab(id:string){setTab(id);setMenu(false);setQuery('');setFilter('All');history.replaceState(null,'',`/app?view=${id}`);}
  function update(next:ReturnType<typeof readDemo>){setDemo(next);if(!saveDemo(next))setNotice({title:'Preview updated for this visit',body:'Your browser could not save the preview. Changes will reset when this page is reloaded.'});}
  function decide(status:'Approved draft'|'Dismissed'){
    if(!selected)return;
    update({...demo,requests:demo.requests.map(r=>r.id===selected.id?{...r,status}:r),activity:[`${selected.id} · ${status} in preview`,...demo.activity]});
    setSelected(null);setNotice({title:status==='Approved draft'?'Draft approved in preview':'Request dismissed in preview',body:status==='Approved draft'?'The example draft has been marked approved. No real job was created, no transaction was signed, and no funds moved. The live flow will review funding separately.':'The sample request has been removed from your review queue. No real request was changed.'});
  }
  const visible=demo.requests.filter(r=>(filter==='All'||r.status===filter)&&`${r.title} ${r.id} ${r.agentId}`.toLowerCase().includes(query.toLowerCase()));
  function requestRows(items:RequestItem[]){return <div className="request-list">{items.length?items.map(r=>{const a=agents.find(a=>a.id===r.agentId)!;return <button className="request-row" key={r.id} onClick={()=>setSelected(r)}><Portrait agent={a}/><span className="request-title"><strong>{r.title}</strong><small>{a.name} by LiegeAgents · {r.id}</small></span><span className={`status status-${r.status.toLowerCase().replaceAll(' ','-')}`}>{r.status}</span><span className="request-budget">{r.budget}<small>{r.asset}</small></span><ArrowUpRight size={17}/></button>}):<div className="empty"><Inbox size={28}/><h3>No requests here.</h3><p>Try another search or status filter.</p><Button secondary onClick={()=>{setQuery('');setFilter('All');}}>Clear filters</Button></div>}</div>;}
  return <div className="dashboard"><aside className={`sidebar ${menu?'sidebar-open':''}`}><Logo/><div className="workspace-switch"><span className="user-avatar">D</span><span>Demo workspace<small>Super Agents preview</small></span></div><span className="nav-label">YOUR WORKSPACE</span><nav>{tabs.map(t=><button className={tab===t.id?'active':''} key={t.id} onClick={()=>changeTab(t.id)}><t.icon size={18}/>{t.label}{t.id==='requests'&&pending.length>0&&<b>{pending.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><span className="x-symbol">𝕏</span><strong>Your next job starts<br/>with a mention.</strong><span>{BOT}</span><a href="/#how-it-works">See how it works <ArrowUpRight size={13}/></a></div><a href={`${LIEGE}/app`}><ArrowUpRight size={16}/> Main Liege workspace</a><button onClick={()=>{try{sessionStorage.removeItem('liege-superagents-preview-v1');}catch{/* Preview can still be exited. */}location.assign('/');}}><LogOut size={16}/> Exit preview</button></div></aside><div className="dashboard-body"><header className="dash-top"><button className="icon-button menu-toggle" aria-label="Toggle workspace navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button><span>Workspace <ChevronRight size={13}/> {tabs.find(t=>t.id===tab)?.label}</span><div><span className="preview-label">Demo workspace</span><button className="user-avatar" onClick={()=>changeTab('settings')} aria-label="Account settings">D</button></div></header><main className="dash-main"><div className="demo-banner"><ShieldCheck size={15}/><span>Frontend preview. All requests and activity below are sample data. No live account access or transactions.</span></div><div className="dash-heading"><div><span className="eyebrow">SUPER AGENTS / {tab.toUpperCase()}</span><h1>{({overview:'Good ideas, in motion.',requests:'Your next decisions.',agents:'Find your kind of brilliant.',activity:'Every step, accounted for.',settings:'Your account. Your rules.'} as Record<string,string>)[tab]}</h1><p>{({overview:'A clear view of your agents, requests, and what needs you next.',requests:'From an X mention to a brief you can review.',agents:'Meet the flagship team, or start shaping your own Super Agent.',activity:'Follow the trail from request to decision.',settings:'Manage your identities and the access you give Super Agents.'} as Record<string,string>)[tab]}</p></div>{tab==='agents'?<Button onClick={()=>setPublish(true)}><Plus size={15}/> Create an agent draft</Button>:<Button secondary onClick={()=>changeTab('agents')}>Explore agents <ArrowUpRight size={16}/></Button>}</div>
    {tab==='overview'&&<><div className="metric-grid">{[{label:'Awaiting your review',value:pending.length,foot:'Requests ready for a decision',icon:Inbox},{label:'Work in progress',value:demo.requests.filter(r=>r.status==='In progress').length,foot:'Sample jobs with your agents',icon:Activity},{label:'Deliverables ready',value:demo.requests.filter(r=>r.status==='Delivered').length,foot:'Completed example work',icon:FileText}].map(m=><button className="metric" key={m.label} onClick={()=>{changeTab('requests');setFilter(m.label==='Awaiting your review'?'Needs review':m.label==='Work in progress'?'In progress':'Delivered');}}><span>{m.label}<m.icon size={17}/></span><strong>{m.value.toString().padStart(2,'0')}</strong><small>{m.foot}<ArrowUpRight size={13}/></small></button>)}</div><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">THE NEXT MOVE IS YOURS</span><h2>Ready for review <small>{pending.length}</small></h2></div><button onClick={()=>changeTab('requests')} className="text-link">View all <ArrowUpRight size={14}/></button></div>{requestRows(pending)}</section><section className="connect-panel"><span className="x-symbol">𝕏</span><h2>A timeline.<br/>A starting line.</h2><p>Mention the bot with a task, an agent, and a budget. Your proposal will meet you here.</p><div>{BOT}<br/><span>hire Anna to research…</span></div><a href="/auth" className="text-link">Preview account setup <ArrowRight size={14}/></a></section></div><div className="panel-heading featured-heading"><div><span className="eyebrow">GET TO KNOW THE TEAM</span><h2>A specialist for your next move.</h2></div><button className="text-link" onClick={()=>changeTab('agents')}>Meet all five <ArrowUpRight size={14}/></button></div><div className="featured-agents">{agents.slice(0,3).map(a=><button key={a.id} onClick={()=>setAgent(a)}><Portrait agent={a}/><span><strong>{a.name} by LiegeAgents</strong><small>{a.category}</small></span><ArrowUpRight size={16}/></button>)}</div></>}
    {tab==='requests'&&<section className="panel"><div className="request-toolbar"><div className="filters">{['All','Needs review','Approved draft','In progress','Delivered','Dismissed'].map(s=><button key={s} className={filter===s?'selected':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><label className="search"><Search size={15}/><input aria-label="Search requests" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search requests…"/></label></div>{requestRows(visible)}</section>}
    {tab==='agents'&&<><span className="preview-label catalog-label">Flagship lineup · Service execution not connected</span><AgentCards onSelect={setAgent}/><section className="panel drafts-panel"><div className="panel-heading"><h2>Your agent drafts</h2><span className="muted small">Saved in this browser session only</span></div>{demo.drafts.length?demo.drafts.map((d,i)=><div className="draft-row" key={i}><Users size={19}/><span><strong>{d.name}</strong><small>{d.service}</small></span><span className="status">Local draft</span></div>):<div className="empty"><Users size={26}/><h3>The next agent could be yours.</h3><p>Shape your offering in the builder preview.</p><Button secondary onClick={()=>setPublish(true)}>Create an agent draft <Plus size={15}/></Button></div>}</section></>}
    {tab==='activity'&&<section className="panel"><div className="panel-heading"><h2>Workspace activity</h2><span className="preview-label">Example events</span></div>{demo.activity.map((a,i)=><div className="activity-row" key={i}><span><Check size={16}/></span><div><strong>{a}</strong><small>{i===0?'Latest preview event':'Earlier in this preview'}</small></div></div>)}<div className="activity-row"><span><FileText size={16}/></span><div><strong>SA-1035 · Example deliverable received</strong><small>Daniel by LiegeAgents · Sample event</small></div></div></section>}
    {tab==='settings'&&<div className="settings-grid"><section className="panel"><div className="panel-heading"><h2>Connected identities</h2><Link2 size={19}/></div><div className="settings-content"><div className="identity-row"><span className="x-symbol">𝕏</span><span>@demo_liege<small>Sample X identity · Not authenticated</small></span><span className="status">Preview</span></div><div className="identity-row"><Wallet size={23}/><span>Demo Liege account<small>No wallet connected</small></span><span className="status">Preview</span></div><a className="text-link" href="/auth">Walk through onboarding <ArrowRight size={15}/></a></div></section><section className="panel"><div className="panel-heading"><h2>Permissions</h2><ShieldCheck size={19}/></div><div className="settings-content"><div className="permissions">{permissions.map(p=><div key={p.title}><Check size={16}/><span><strong>{p.title}</strong><small>{p.detail}</small></span></div>)}</div><p className="scope-note">These are proposed scopes. No real permission grant exists in this preview.</p><Button secondary onClick={()=>setRevoke(true)}>Reset preview connections</Button></div></section></div>}
    <div className="dash-footer"><Logo/><span>Your agents. Your call.</span></div></main></div>
    {selected&&<Modal title="Review request" onClose={()=>setSelected(null)}><div className="preview-label">Example request · {selected.id}</div><h3 className="serif">{selected.title}</h3><div className="review-agent"><Portrait agent={agents.find(a=>a.id===selected.agentId)!}/><span><strong>{agents.find(a=>a.id===selected.agentId)!.name} by LiegeAgents</strong><small>Suggested match based on the service category</small></span></div><h4>The original request</h4><blockquote>{selected.source}</blockquote><h4>Proposed brief</h4><p>{selected.brief}</p><dl className="review-terms"><div><dt>Budget</dt><dd>{selected.budget} {selected.asset}</dd></div><div><dt>Delivery</dt><dd>{selected.due}</dd></div><div><dt>Evaluation</dt><dd>To be confirmed before funding</dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div></dl><p className="scope-note">Approving this preview only updates a sample draft. Live funding will require a separate wallet confirmation.</p>{selected.status==='Needs review'?<div className="dialog-actions"><Button secondary onClick={()=>decide('Dismissed')}>Dismiss example</Button><Button onClick={()=>decide('Approved draft')}>Approve example draft <Check size={15}/></Button></div>:<Button secondary onClick={()=>setSelected(null)}>Close request</Button>}</Modal>}
    {agent&&<AgentDetail agent={agent} onClose={()=>setAgent(null)}/>}
    {publish&&<Modal title="Your next Super Agent" onClose={()=>setPublish(false)}><p>Create a local offering draft. Publishing and connecting a runtime will become available with the backend.</p><form className="agent-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const name=String(form.get('name')||'').trim(),service=String(form.get('service')||'').trim();if(!name||!service)return;update({...demo,drafts:[...demo.drafts,{name,service}],activity:[`Agent draft created · ${name}`,...demo.activity]});setPublish(false);setNotice({title:'Agent draft saved',body:'Your offering is saved for this browser session. It has not been published to Liege or X.'});}}><label>Agent name<input name="name" required maxLength={60} placeholder="e.g. Maya Research"/></label><label>What does your agent offer?<textarea name="service" required maxLength={600} rows={4} placeholder="Describe the work, expected inputs, and what your client receives."/></label><Button type="submit">Save preview draft <ArrowRight size={15}/></Button></form></Modal>}
    {notice&&<Modal title={notice.title} onClose={()=>setNotice(null)}><p>{notice.body}</p><Button onClick={()=>setNotice(null)}>Got it <Check size={15}/></Button></Modal>}
    {revoke&&<Modal title="Reset this preview?" onClose={()=>setRevoke(false)}><p>This clears your sample approvals, agent drafts, and walkthrough progress from this browser session. No real account is affected.</p><div className="dialog-actions"><Button secondary onClick={()=>setRevoke(false)}>Keep preview</Button><Button onClick={()=>{try{sessionStorage.removeItem('liege-superagents-preview-v1');}catch{/* Navigation still works. */}location.assign('/auth');}}>Reset preview</Button></div></Modal>}
  </div>;
}
function App() { const path = location.pathname.replace(/\/$/,'') || '/'; return path==='/'?<Landing/>:path==='/auth'?<Onboarding/>:path==='/app'?<Dashboard/>:<div className="not-found"><Logo/><h1>A small detour.</h1><p>This page doesn’t exist. Let’s get you back to the agents.</p><a className="button" href="/">Back to home <ArrowRight size={16}/></a></div>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
