/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DocsTopicRouteImport } from './routes/docs.$topic'
import { Route as MarketplaceAgentRouteImport } from './routes/marketplace.$agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTopicRoute = DocsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => DocsRoute,
} as any)
const MarketplaceAgentRoute = MarketplaceAgentRouteImport.update({
  id: '/$agent',
  path: '/$agent',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/baseline': typeof BaselineRoute
  '/docs': typeof DocsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/whitepaper': typeof WhitepaperRoute
  '/zh': typeof ZhRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/marketplace/$agent': typeof MarketplaceAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/baseline': typeof BaselineRoute
  '/docs': typeof DocsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/whitepaper': typeof WhitepaperRoute
  '/zh': typeof ZhRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/marketplace/$agent': typeof MarketplaceAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/baseline': typeof BaselineRoute
  '/docs': typeof DocsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/whitepaper': typeof WhitepaperRoute
  '/zh': typeof ZhRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/$topic': typeof DocsTopicRoute
  '/marketplace/$agent': typeof MarketplaceAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/baseline'
    | '/docs'
    | '/marketplace'
    | '/roadmap'
    | '/whitepaper'
    | '/zh'
    | '/api/$'
    | '/docs/$topic'
    | '/marketplace/$agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/baseline'
    | '/docs'
    | '/marketplace'
    | '/roadmap'
    | '/whitepaper'
    | '/zh'
    | '/api/$'
    | '/docs/$topic'
    | '/marketplace/$agent'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/baseline'
    | '/docs'
    | '/marketplace'
    | '/roadmap'
    | '/whitepaper'
    | '/zh'
    | '/api/$'
    | '/docs/$topic'
    | '/marketplace/$agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BaselineRoute: typeof BaselineRoute
  DocsRoute: typeof DocsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  WhitepaperRoute: typeof WhitepaperRoute
  ZhRoute: typeof ZhRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$topic': {
      id: '/docs/$topic'
      path: '/$topic'
      fullPath: '/docs/$topic'
      preLoaderRoute: typeof DocsTopicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/marketplace/$agent': {
      id: '/marketplace/$agent'
      path: '/$agent'
      fullPath: '/marketplace/$agent'
      preLoaderRoute: typeof MarketplaceAgentRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface DocsRouteChildren {
  DocsTopicRoute: typeof DocsTopicRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsTopicRoute: DocsTopicRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceAgentRoute: typeof MarketplaceAgentRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceAgentRoute: MarketplaceAgentRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BaselineRoute: BaselineRoute,
  DocsRoute: DocsRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  WhitepaperRoute: WhitepaperRoute,
  ZhRoute: ZhRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
